"""Membuat seluruh folder proyek Digital Twin Tangki Air.

Cara pakai:
    python buat_proyek.py

Hasilnya folder `digital-twin-tangki-air/` di lokasi yang sama dengan file ini.
Folder itu siap di-upload ke GitHub (drag & drop folder, atau pakai git).
"""
import os

FILES = {'.gitignore': '__pycache__/\n*.pyc\n.venv/\nvenv/\ndata/*.db\n.pytest_cache/\n.env\n',
 'README.md': '# Digital Twin Tangki Air\n'
              '\n'
              'Kerangka dasar (boilerplate) proyek **Perancangan Digital Twin Tangki Air untuk '
              'Monitoring Ketinggian dan Kondisi Air Secara Real-Time**.\n'
              'Berisi struktur folder, inisialisasi database, API simulasi sensor, dan dashboard '
              'awal yang sudah bisa dijalankan.\n'
              '\n'
              '**Teknologi:** Python 3.10+, Flask, SQLite, HTML/CSS/JavaScript (tanpa framework '
              'tambahan).\n'
              '\n'
              '## Menjalankan\n'
              '\n'
              '```bash\n'
              'python -m venv .venv\n'
              '# Windows:  .venv\\Scripts\\activate\n'
              '# Mac/Linux: source .venv/bin/activate\n'
              'pip install -r requirements.txt\n'
              'python run.py\n'
              '```\n'
              '\n'
              'Buka http://127.0.0.1:5000. Database `data/tangki.db` dibuat otomatis saat pertama '
              'dijalankan.\n'
              'Data simulasi masuk setiap 5 detik (atur di `config.py`).\n'
              '\n'
              '## Menjalankan tes\n'
              '\n'
              '```bash\n'
              'python -m pytest\n'
              '```\n'
              '\n'
              '## Struktur folder\n'
              '\n'
              '```\n'
              'digital-twin-tangki-air/\n'
              '├── run.py                 # titik masuk aplikasi\n'
              '├── config.py              # pengaturan, ambang batas notifikasi, sumber data '
              'sensor\n'
              '├── requirements.txt\n'
              '├── app/\n'
              '│   ├── __init__.py        # create_app()\n'
              '│   ├── db.py              # koneksi & inisialisasi SQLite\n'
              '│   ├── schema.sql         # tabel + data awal\n'
              '│   ├── routes.py          # halaman dan REST API\n'
              '│   ├── ingest.py          # validasi, simpan data sensor, poller API simulasi\n'
              '│   ├── anomaly.py         # aturan deteksi kondisi kritis\n'
              '│   ├── simulator.py       # API simulasi sensor (/sim/sensor)\n'
              '│   ├── templates/index.html\n'
              '│   └── static/{css,js}/\n'
              '├── data/                  # file database (tidak masuk git)\n'
              '├── docs/                  # dokumen Sprint 1\n'
              '└── tests/\n'
              '```\n'
              '\n'
              '## Endpoint\n'
              '\n'
              '| Method | URL | Fungsi | PBI |\n'
              '| --- | --- | --- | --- |\n'
              '| GET / PUT | `/api/tank-config` | Baca / ubah konfigurasi tangki | 01, 08 |\n'
              '| POST | `/api/sensor` | Input data sensor (JSON) | 02, 09 |\n'
              '| GET | `/api/sensor/latest` | Data terakhir + peringatan aktif | 03, 04 |\n'
              '| GET | `/api/history?start=&end=&limit=` | Riwayat, bisa difilter waktu | 06, 07 '
              '|\n'
              '| GET | `/api/notifications` | Catatan notifikasi | 05, 10 |\n'
              '| GET | `/sim/sensor` | API simulasi sensor | 11 |\n'
              '\n'
              'Contoh input manual:\n'
              '\n'
              '```bash\n'
              'curl -X POST http://127.0.0.1:5000/api/sensor -H "Content-Type: application/json" '
              '\\\n'
              '  -d \'{"level_cm": 30, "temperature_c": 27, "ph": 7.1, "turbidity_ntu": 2}\'\n'
              '```\n'
              '\n'
              '## Status terhadap Sprint 1 Backlog\n'
              '\n'
              'Kerangka ini sudah memuat versi dasar dari PBI-01 sampai PBI-11 (skema database, '
              'simulator, penyimpanan,\n'
              'deteksi anomali, dashboard, riwayat). Tugas tim selanjutnya adalah menyempurnakan, '
              'misalnya\n'
              'visualisasi tangki yang lebih detail (T-11), indikator kualitas air (T-14), dan '
              'pengujian lebih lengkap (T-19).\n'
              '\n'
              '## Catatan\n'
              '\n'
              '- Belum ada login; tabel `users` sudah disiapkan untuk PBI-12 (Sprint 2).\n'
              '- Waktu disimpan sesuai jam lokal komputer server.\n'
              '- Jika sensor fisik sudah ada, ubah `SENSOR_API_URL` di `config.py` atau kirim data '
              'langsung ke `POST /api/sensor`.\n',
 'app/__init__.py': 'from flask import Flask\n'
                    '\n'
                    'from . import db\n'
                    '\n'
                    '\n'
                    'def create_app(overrides=None):\n'
                    '    app = Flask(__name__)\n'
                    '    app.config.from_object("config")\n'
                    '    if overrides:\n'
                    '        app.config.update(overrides)\n'
                    '\n'
                    '    db.init_app(app)\n'
                    '\n'
                    '    from .routes import bp\n'
                    '    from .simulator import sim_bp\n'
                    '\n'
                    '    app.register_blueprint(bp)\n'
                    '    app.register_blueprint(sim_bp)\n'
                    '\n'
                    '    with app.app_context():\n'
                    '        db.init_db()\n'
                    '\n'
                    '    if app.config.get("START_POLLER"):\n'
                    '        from .ingest import start_poller\n'
                    '\n'
                    '        start_poller(app)\n'
                    '\n'
                    '    return app\n',
 'app/anomaly.py': '"""Aturan deteksi kondisi kritis / anomali (PBI-05)."""\n'
                   'from flask import current_app\n'
                   '\n'
                   '\n'
                   'def check_reading(reading):\n'
                   '    """Mengembalikan daftar peringatan untuk satu pembacaan sensor."""\n'
                   '    c = current_app.config\n'
                   '    alerts = []\n'
                   '\n'
                   '    if reading["level_pct"] < c["LEVEL_LOW_PCT"]:\n'
                   '        alerts.append(("level_low", "critical",\n'
                   '                       f"Level air rendah ({reading[\'level_pct\']:.0f}%)."))\n'
                   '    elif reading["level_pct"] > c["LEVEL_HIGH_PCT"]:\n'
                   '        alerts.append(("level_high", "warning",\n'
                   '                       f"Tangki hampir penuh '
                   '({reading[\'level_pct\']:.0f}%)."))\n'
                   '\n'
                   '    if not c["TEMP_MIN_C"] <= reading["temperature_c"] <= c["TEMP_MAX_C"]:\n'
                   '        alerts.append(("temp", "warning",\n'
                   '                       f"Suhu air di luar batas '
                   '({reading[\'temperature_c\']:.1f} °C)."))\n'
                   '\n'
                   '    if not c["PH_MIN"] <= reading["ph"] <= c["PH_MAX"]:\n'
                   '        alerts.append(("ph", "critical",\n'
                   '                       f"pH air di luar batas ({reading[\'ph\']:.2f})."))\n'
                   '\n'
                   '    if reading["turbidity_ntu"] > c["TURBIDITY_MAX_NTU"]:\n'
                   '        alerts.append(("turbidity", "warning",\n'
                   '                       f"Air keruh ({reading[\'turbidity_ntu\']:.1f} NTU)."))\n'
                   '\n'
                   '    return [{"kind": k, "severity": s, "message": m} for k, s, m in alerts]\n',
 'app/db.py': 'import os\n'
              'import sqlite3\n'
              '\n'
              'from flask import current_app, g\n'
              '\n'
              '\n'
              'def get_db():\n'
              '    if "db" not in g:\n'
              '        g.db = sqlite3.connect(current_app.config["DB_PATH"])\n'
              '        g.db.row_factory = sqlite3.Row\n'
              '    return g.db\n'
              '\n'
              '\n'
              'def close_db(_exc=None):\n'
              '    conn = g.pop("db", None)\n'
              '    if conn is not None:\n'
              '        conn.close()\n'
              '\n'
              '\n'
              'def init_db():\n'
              '    """Membuat tabel (jika belum ada) dan mengisi data awal."""\n'
              '    os.makedirs(os.path.dirname(current_app.config["DB_PATH"]), exist_ok=True)\n'
              '    conn = get_db()\n'
              '    with current_app.open_resource("schema.sql") as f:\n'
              '        conn.executescript(f.read().decode("utf-8"))\n'
              '    conn.commit()\n'
              '\n'
              '\n'
              'def init_app(app):\n'
              '    app.teardown_appcontext(close_db)\n',
 'app/ingest.py': '"""Input data sensor, penyimpanan rekaman, dan pengambilan data dari API '
                  'simulasi\n'
                  '(PBI-02, PBI-09, PBI-11)."""\n'
                  'import json\n'
                  'import logging\n'
                  'import threading\n'
                  'import time\n'
                  'import urllib.request\n'
                  '\n'
                  'from flask import current_app\n'
                  '\n'
                  'from .anomaly import check_reading\n'
                  'from .db import get_db\n'
                  '\n'
                  'log = logging.getLogger(__name__)\n'
                  'FIELDS = ("level_cm", "temperature_c", "ph", "turbidity_ntu")\n'
                  '\n'
                  '\n'
                  'class ValidationError(ValueError):\n'
                  '    pass\n'
                  '\n'
                  '\n'
                  'def validate(payload):\n'
                  '    if not isinstance(payload, dict):\n'
                  '        raise ValidationError("Data harus berupa objek JSON.")\n'
                  '    data = {}\n'
                  '    for f in FIELDS:\n'
                  '        try:\n'
                  '            data[f] = float(payload[f])\n'
                  '        except (KeyError, TypeError, ValueError):\n'
                  '            raise ValidationError(f"Field \'{f}\' wajib diisi dengan angka.")\n'
                  '    if data["level_cm"] < 0:\n'
                  '        raise ValidationError("level_cm tidak boleh negatif.")\n'
                  '    if not 0 <= data["ph"] <= 14:\n'
                  '        raise ValidationError("ph harus di antara 0 dan 14.")\n'
                  '    if data["turbidity_ntu"] < 0:\n'
                  '        raise ValidationError("turbidity_ntu tidak boleh negatif.")\n'
                  '    return data\n'
                  '\n'
                  '\n'
                  'def get_tank_config(conn):\n'
                  '    return dict(conn.execute("SELECT * FROM tank_config WHERE id = '
                  '1").fetchone())\n'
                  '\n'
                  '\n'
                  'def _store_notification(conn, alert):\n'
                  '    cooldown = f"-{int(current_app.config[\'NOTIF_COOLDOWN_S\'])} seconds"\n'
                  '    recent = conn.execute(\n'
                  '        "SELECT 1 FROM notifications WHERE kind = ? "\n'
                  '        "AND created_at >= datetime(\'now\', \'localtime\', ?)",\n'
                  '        (alert["kind"], cooldown),\n'
                  '    ).fetchone()\n'
                  '    if recent is None:\n'
                  '        conn.execute(\n'
                  '            "INSERT INTO notifications (kind, severity, message) VALUES (?, ?, '
                  '?)",\n'
                  '            (alert["kind"], alert["severity"], alert["message"]),\n'
                  '        )\n'
                  '\n'
                  '\n'
                  'def save_reading(payload):\n'
                  '    """Validasi, simpan rekaman sensor, lalu jalankan deteksi anomali."""\n'
                  '    data = validate(payload)\n'
                  '    conn = get_db()\n'
                  '    cfg = get_tank_config(conn)\n'
                  '\n'
                  '    pct = max(0.0, min(100.0, data["level_cm"] / cfg["height_cm"] * 100))\n'
                  '    volume = cfg["capacity_l"] * pct / 100\n'
                  '\n'
                  '    cur = conn.execute(\n'
                  '        "INSERT INTO sensor_readings "\n'
                  '        "(level_cm, level_pct, volume_l, temperature_c, ph, turbidity_ntu) "\n'
                  '        "VALUES (?, ?, ?, ?, ?, ?)",\n'
                  '        (data["level_cm"], pct, volume, data["temperature_c"], data["ph"],\n'
                  '         data["turbidity_ntu"]),\n'
                  '    )\n'
                  '    row = conn.execute("SELECT * FROM sensor_readings WHERE id = ?",\n'
                  '                       (cur.lastrowid,)).fetchone()\n'
                  '    reading = dict(row)\n'
                  '    alerts = check_reading(reading)\n'
                  '    for a in alerts:\n'
                  '        _store_notification(conn, a)\n'
                  '    conn.commit()\n'
                  '    return reading, alerts\n'
                  '\n'
                  '\n'
                  'def fetch_sensor():\n'
                  '    """Mengambil satu pembacaan dari API sensor (simulasi)."""\n'
                  '    url = current_app.config["SENSOR_API_URL"]\n'
                  '    with urllib.request.urlopen(url, timeout=5) as resp:\n'
                  '        return json.loads(resp.read().decode("utf-8"))\n'
                  '\n'
                  '\n'
                  'def start_poller(app):\n'
                  '    """Menjalankan thread yang mengambil data sensor secara berkala."""\n'
                  '    def loop():\n'
                  '        time.sleep(2)  # tunggu server siap\n'
                  '        while True:\n'
                  '            try:\n'
                  '                with app.app_context():\n'
                  '                    save_reading(fetch_sensor())\n'
                  '            except Exception as exc:  # jangan hentikan thread karena satu '
                  'kegagalan\n'
                  '                log.warning("Gagal mengambil data sensor: %s", exc)\n'
                  '            time.sleep(app.config["POLL_INTERVAL_S"])\n'
                  '\n'
                  '    threading.Thread(target=loop, daemon=True, name="sensor-poller").start()\n',
 'app/routes.py': '"""Halaman dan REST API Sprint 1."""\n'
                  'from flask import Blueprint, jsonify, render_template, request\n'
                  '\n'
                  'from .anomaly import check_reading\n'
                  'from .db import get_db\n'
                  'from .ingest import ValidationError, get_tank_config, save_reading\n'
                  '\n'
                  'bp = Blueprint("main", __name__)\n'
                  '\n'
                  '\n'
                  '@bp.get("/")\n'
                  'def dashboard():\n'
                  '    return render_template("index.html")\n'
                  '\n'
                  '\n'
                  '# --- Konfigurasi tangki (PBI-01, PBI-08) ---\n'
                  '@bp.get("/api/tank-config")\n'
                  'def read_tank_config():\n'
                  '    return jsonify(get_tank_config(get_db()))\n'
                  '\n'
                  '\n'
                  '@bp.put("/api/tank-config")\n'
                  'def update_tank_config():\n'
                  '    body = request.get_json(silent=True) or {}\n'
                  '    try:\n'
                  '        values = {k: float(body[k]) for k in ("capacity_l", "height_cm", '
                  '"diameter_cm")}\n'
                  '    except (KeyError, TypeError, ValueError):\n'
                  '        return jsonify(error="Kapasitas, tinggi, dan diameter wajib diisi '
                  'dengan angka."), 400\n'
                  '    if any(v <= 0 for v in values.values()):\n'
                  '        return jsonify(error="Kapasitas, tinggi, dan diameter harus lebih dari '
                  '0."), 400\n'
                  '\n'
                  '    name = str(body.get("name", "")).strip() or "Tangki Utama"\n'
                  '    conn = get_db()\n'
                  '    conn.execute(\n'
                  '        "UPDATE tank_config SET name = ?, capacity_l = ?, height_cm = ?, '
                  'diameter_cm = ?, "\n'
                  '        "updated_at = datetime(\'now\', \'localtime\') WHERE id = 1",\n'
                  '        (name, values["capacity_l"], values["height_cm"], '
                  'values["diameter_cm"]),\n'
                  '    )\n'
                  '    conn.commit()\n'
                  '    return jsonify(get_tank_config(conn))\n'
                  '\n'
                  '\n'
                  '# --- Data sensor (PBI-02, PBI-03, PBI-04) ---\n'
                  '@bp.post("/api/sensor")\n'
                  'def post_sensor():\n'
                  '    try:\n'
                  '        reading, alerts = save_reading(request.get_json(silent=True))\n'
                  '    except ValidationError as exc:\n'
                  '        return jsonify(error=str(exc)), 400\n'
                  '    return jsonify(reading=reading, alerts=alerts), 201\n'
                  '\n'
                  '\n'
                  '@bp.get("/api/sensor/latest")\n'
                  'def latest_sensor():\n'
                  '    row = get_db().execute(\n'
                  '        "SELECT * FROM sensor_readings ORDER BY id DESC LIMIT 1").fetchone()\n'
                  '    if row is None:\n'
                  '        return jsonify(reading=None, alerts=[])\n'
                  '    reading = dict(row)\n'
                  '    return jsonify(reading=reading, alerts=check_reading(reading))\n'
                  '\n'
                  '\n'
                  '# --- Riwayat & pencarian rentang waktu (PBI-06, PBI-07) ---\n'
                  'def _normalize_time(value, end=False):\n'
                  '    value = value.strip().replace("T", " ")\n'
                  '    if len(value) == 10:  # hanya tanggal\n'
                  '        return value + (" 23:59:59" if end else " 00:00:00")\n'
                  '    if len(value) == 16:  # tanggal + jam:menit\n'
                  '        return value + (":59" if end else ":00")\n'
                  '    return value\n'
                  '\n'
                  '\n'
                  '@bp.get("/api/history")\n'
                  'def history():\n'
                  '    sql, args = "SELECT * FROM sensor_readings WHERE 1=1", []\n'
                  '    if request.args.get("start"):\n'
                  '        sql += " AND recorded_at >= ?"\n'
                  '        args.append(_normalize_time(request.args["start"]))\n'
                  '    if request.args.get("end"):\n'
                  '        sql += " AND recorded_at <= ?"\n'
                  '        args.append(_normalize_time(request.args["end"], end=True))\n'
                  '    try:\n'
                  '        limit = max(1, min(int(request.args.get("limit", 100)), 1000))\n'
                  '    except ValueError:\n'
                  '        limit = 100\n'
                  '    sql += " ORDER BY id DESC LIMIT ?"\n'
                  '    args.append(limit)\n'
                  '    rows = get_db().execute(sql, args).fetchall()\n'
                  '    return jsonify([dict(r) for r in rows])\n'
                  '\n'
                  '\n'
                  '# --- Notifikasi (PBI-05, PBI-10) ---\n'
                  '@bp.get("/api/notifications")\n'
                  'def notifications():\n'
                  '    try:\n'
                  '        limit = max(1, min(int(request.args.get("limit", 20)), 200))\n'
                  '    except ValueError:\n'
                  '        limit = 20\n'
                  '    rows = get_db().execute(\n'
                  '        "SELECT * FROM notifications ORDER BY id DESC LIMIT ?", '
                  '(limit,)).fetchall()\n'
                  '    return jsonify([dict(r) for r in rows])\n',
 'app/schema.sql': '-- Skema database Sprint 1 (PBI-08, PBI-09, PBI-10)\n'
                   '\n'
                   'CREATE TABLE IF NOT EXISTS users (\n'
                   '    id         INTEGER PRIMARY KEY AUTOINCREMENT,\n'
                   '    username   TEXT NOT NULL UNIQUE,\n'
                   "    role       TEXT NOT NULL DEFAULT 'operator',\n"
                   "    created_at TEXT NOT NULL DEFAULT (datetime('now', 'localtime'))\n"
                   ');\n'
                   '\n'
                   'CREATE TABLE IF NOT EXISTS tank_config (\n'
                   '    id          INTEGER PRIMARY KEY CHECK (id = 1),\n'
                   '    name        TEXT NOT NULL,\n'
                   '    capacity_l  REAL NOT NULL CHECK (capacity_l > 0),\n'
                   '    height_cm   REAL NOT NULL CHECK (height_cm > 0),\n'
                   '    diameter_cm REAL NOT NULL CHECK (diameter_cm > 0),\n'
                   "    updated_at  TEXT NOT NULL DEFAULT (datetime('now', 'localtime'))\n"
                   ');\n'
                   '\n'
                   'CREATE TABLE IF NOT EXISTS sensor_readings (\n'
                   '    id            INTEGER PRIMARY KEY AUTOINCREMENT,\n'
                   "    recorded_at   TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
                   '    level_cm      REAL NOT NULL,\n'
                   '    level_pct     REAL NOT NULL,\n'
                   '    volume_l      REAL NOT NULL,\n'
                   '    temperature_c REAL NOT NULL,\n'
                   '    ph            REAL NOT NULL,\n'
                   '    turbidity_ntu REAL NOT NULL\n'
                   ');\n'
                   'CREATE INDEX IF NOT EXISTS idx_readings_time ON sensor_readings '
                   '(recorded_at);\n'
                   '\n'
                   'CREATE TABLE IF NOT EXISTS notifications (\n'
                   '    id         INTEGER PRIMARY KEY AUTOINCREMENT,\n'
                   "    created_at TEXT NOT NULL DEFAULT (datetime('now', 'localtime')),\n"
                   '    kind       TEXT NOT NULL,\n'
                   '    severity   TEXT NOT NULL,\n'
                   '    message    TEXT NOT NULL\n'
                   ');\n'
                   'CREATE INDEX IF NOT EXISTS idx_notif_kind_time ON notifications (kind, '
                   'created_at);\n'
                   '\n'
                   '-- Data awal\n'
                   'INSERT OR IGNORE INTO tank_config (id, name, capacity_l, height_cm, '
                   'diameter_cm)\n'
                   "VALUES (1, 'Tangki Utama', 1000, 150, 100);\n"
                   '\n'
                   "INSERT OR IGNORE INTO users (username, role) VALUES ('admin', 'admin');\n",
 'app/simulator.py': '"""API simulasi sensor tangki air (PBI-11). Diganti sensor fisik di Sprint '
                     'berikutnya."""\n'
                     'import random\n'
                     '\n'
                     'from flask import Blueprint, jsonify\n'
                     '\n'
                     'from .db import get_db\n'
                     '\n'
                     'sim_bp = Blueprint("sim", __name__, url_prefix="/sim")\n'
                     '_state = {"level": None, "direction": -1}\n'
                     '\n'
                     '\n'
                     '@sim_bp.get("/sensor")\n'
                     'def sensor():\n'
                     '    height = get_db().execute(\n'
                     '        "SELECT height_cm FROM tank_config WHERE id = '
                     '1").fetchone()["height_cm"]\n'
                     '\n'
                     '    if _state["level"] is None or _state["level"] > height:\n'
                     '        _state["level"] = height * 0.7\n'
                     '\n'
                     '    _state["level"] += _state["direction"] * random.uniform(0.5, 3.0)\n'
                     '    if _state["level"] <= height * 0.12:\n'
                     '        _state["direction"] = 1\n'
                     '    elif _state["level"] >= height * 0.95:\n'
                     '        _state["direction"] = -1\n'
                     '    _state["level"] = max(0.0, min(height, _state["level"]))\n'
                     '\n'
                     '    turbidity = random.uniform(0.5, 3.0)\n'
                     '    if random.random() < 0.05:  # sesekali air keruh agar notifikasi bisa '
                     'dicoba\n'
                     '        turbidity = random.uniform(6.0, 9.0)\n'
                     '\n'
                     '    return jsonify(\n'
                     '        level_cm=round(_state["level"], 1),\n'
                     '        temperature_c=round(random.gauss(27.5, 1.2), 1),\n'
                     '        ph=round(random.gauss(7.2, 0.25), 2),\n'
                     '        turbidity_ntu=round(turbidity, 1),\n'
                     '    )\n',
 'app/static/css/style.css': ':root {\n'
                             '  --ink: #0f2b3a;\n'
                             '  --muted: #5d7280;\n'
                             '  --mist: #eef4f6;\n'
                             '  --line: #d3e0e6;\n'
                             '  --water: #1c8fa6;\n'
                             '  --water-deep: #0b5c73;\n'
                             '  --ok: #2f7d5b;\n'
                             '  --warn: #a86a00;\n'
                             '  --crit: #b93a28;\n'
                             '  --paper: #ffffff;\n'
                             '}\n'
                             '* { box-sizing: border-box; }\n'
                             'body {\n'
                             '  margin: 0;\n'
                             '  font-family: system-ui, -apple-system, "Segoe UI", Roboto, '
                             'sans-serif;\n'
                             '  color: var(--ink);\n'
                             '  background: var(--mist);\n'
                             '  line-height: 1.5;\n'
                             '}\n'
                             '.top { padding: 1.5rem clamp(1rem, 4vw, 3rem) 0.5rem; }\n'
                             'h1 { margin: 0; font-size: 1.6rem; }\n'
                             'h2 { margin: 0 0 0.75rem; font-size: 1.05rem; }\n'
                             '.muted { color: var(--muted); margin: 0.25rem 0 0; font-size: '
                             '0.9rem; }\n'
                             '\n'
                             'main {\n'
                             '  display: grid;\n'
                             '  grid-template-columns: minmax(240px, 320px) 1fr;\n'
                             '  gap: 1.25rem;\n'
                             '  padding: 1rem clamp(1rem, 4vw, 3rem) 3rem;\n'
                             '}\n'
                             '.twin {\n'
                             '  grid-row: span 2;\n'
                             '  background: var(--paper);\n'
                             '  border: 1px solid var(--line);\n'
                             '  border-radius: 16px;\n'
                             '  padding: 1.25rem;\n'
                             '  text-align: center;\n'
                             '}\n'
                             '#tank { width: 100%; max-height: 420px; }\n'
                             '.tank-body { fill: #f4f9fb; }\n'
                             '.tank-outline { fill: none; stroke: var(--water-deep); stroke-width: '
                             '4; }\n'
                             '.water { fill: var(--water); transition: y 1s ease, height 1s ease; '
                             '}\n'
                             '.water.low { fill: var(--crit); }\n'
                             '.level strong { display: block; font-size: 2.6rem; line-height: 1.1; '
                             '}\n'
                             '\n'
                             '.panel {\n'
                             '  background: var(--paper);\n'
                             '  border: 1px solid var(--line);\n'
                             '  border-radius: 8px;\n'
                             '  padding: 1.25rem;\n'
                             '}\n'
                             '.panel.wide { grid-column: 1 / -1; }\n'
                             '\n'
                             '.status-row { display: flex; justify-content: space-between; '
                             'align-items: center; }\n'
                             '.badge { padding: 0.15rem 0.75rem; border-radius: 999px; font-size: '
                             '0.85rem; font-weight: 600; background: var(--mist); }\n'
                             '.badge.ok { background: #dff1e8; color: var(--ok); }\n'
                             '.badge.warning { background: #fbeccc; color: var(--warn); }\n'
                             '.badge.critical { background: #f6dad5; color: var(--crit); }\n'
                             '\n'
                             '.readings { display: grid; grid-template-columns: repeat(auto-fit, '
                             'minmax(110px, 1fr)); gap: 1rem; margin: 0.5rem 0; }\n'
                             '.readings div { border-left: 3px solid var(--water); padding-left: '
                             '0.75rem; }\n'
                             '.readings dt { color: var(--muted); font-size: 0.85rem; }\n'
                             '.readings dd { margin: 0; font-size: 1.4rem; font-weight: 600; }\n'
                             '\n'
                             '.notifs { list-style: none; margin: 0; padding: 0; max-height: '
                             '200px; overflow-y: auto; }\n'
                             '.notifs li { padding: 0.4rem 0; border-bottom: 1px solid '
                             'var(--line); font-size: 0.92rem; }\n'
                             '.notifs li.critical { color: var(--crit); }\n'
                             '.notifs li.warning { color: var(--warn); }\n'
                             '.notifs time { color: var(--muted); margin-right: 0.5rem; font-size: '
                             '0.8rem; }\n'
                             '\n'
                             '.grid { display: grid; gap: 0.75rem; grid-template-columns: '
                             'repeat(auto-fit, minmax(170px, 1fr)); align-items: end; }\n'
                             'label { display: grid; gap: 0.25rem; font-size: 0.9rem; }\n'
                             'input {\n'
                             '  font: inherit; padding: 0.5rem 0.6rem;\n'
                             '  border: 1px solid var(--line); border-radius: 6px; background: '
                             'var(--paper); color: var(--ink);\n'
                             '}\n'
                             'button {\n'
                             '  font: inherit; font-weight: 600; padding: 0.55rem 1rem; cursor: '
                             'pointer;\n'
                             '  border: 0; border-radius: 6px; background: var(--water-deep); '
                             'color: #fff;\n'
                             '}\n'
                             'button.ghost { background: transparent; color: var(--water-deep); '
                             'border: 1px solid var(--line); }\n'
                             'button:hover { filter: brightness(1.1); }\n'
                             ':focus-visible { outline: 3px solid var(--water); outline-offset: '
                             '2px; }\n'
                             '\n'
                             '.table-wrap { overflow-x: auto; margin-top: 1rem; }\n'
                             'table { width: 100%; border-collapse: collapse; font-size: 0.9rem; '
                             '}\n'
                             'th, td { text-align: left; padding: 0.45rem 0.6rem; border-bottom: '
                             '1px solid var(--line); white-space: nowrap; }\n'
                             'th { color: var(--muted); font-weight: 600; }\n'
                             '\n'
                             '@media (max-width: 760px) {\n'
                             '  main { grid-template-columns: 1fr; }\n'
                             '  .twin { grid-row: auto; }\n'
                             '}\n'
                             '@media (prefers-reduced-motion: reduce) {\n'
                             '  .water { transition: none; }\n'
                             '}\n',
 'app/static/js/dashboard.js': 'const $ = (s) => document.querySelector(s);\n'
                               'const REFRESH_MS = 3000;\n'
                               'const T = { top: 20, bottom: 260 }; // batas atas & bawah tangki '
                               'pada SVG\n'
                               '\n'
                               'async function api(url, opts) {\n'
                               '  const res = await fetch(url, opts);\n'
                               '  const data = await res.json();\n'
                               '  if (!res.ok) throw new Error(data.error || "Terjadi '
                               'kesalahan.");\n'
                               '  return data;\n'
                               '}\n'
                               '\n'
                               'function drawWater(pct) {\n'
                               '  const h = ((T.bottom - T.top) * pct) / 100;\n'
                               '  const water = $("#water");\n'
                               '  water.setAttribute("y", T.bottom - h);\n'
                               '  water.setAttribute("height", h);\n'
                               '  water.classList.toggle("low", pct < 20);\n'
                               '}\n'
                               '\n'
                               'function renderLatest({ reading, alerts }) {\n'
                               '  if (!reading) return;\n'
                               '  drawWater(reading.level_pct);\n'
                               '  $("#level-pct").textContent = '
                               '`${reading.level_pct.toFixed(0)}%`;\n'
                               '  $("#level-detail").textContent = `${reading.level_cm.toFixed(1)} '
                               'cm`;\n'
                               '  $("#r-temp").textContent = `${reading.temperature_c.toFixed(1)} '
                               '°C`;\n'
                               '  $("#r-ph").textContent = reading.ph.toFixed(2);\n'
                               '  $("#r-turb").textContent = `${reading.turbidity_ntu.toFixed(1)} '
                               'NTU`;\n'
                               '  $("#r-vol").textContent = `${reading.volume_l.toFixed(0)} L`;\n'
                               '  $("#updated").textContent = `Data terakhir: '
                               '${reading.recorded_at}`;\n'
                               '\n'
                               '  const badge = $("#status");\n'
                               '  const level = alerts.some((a) => a.severity === "critical") ? '
                               '"critical"\n'
                               '              : alerts.length ? "warning" : "ok";\n'
                               '  badge.className = `badge ${level}`;\n'
                               '  badge.textContent = { ok: "Normal", warning: "Perlu perhatian", '
                               'critical: "Kritis" }[level];\n'
                               '}\n'
                               '\n'
                               'function renderNotifs(items) {\n'
                               '  const ul = $("#notifs");\n'
                               '  ul.innerHTML = "";\n'
                               '  if (!items.length) {\n'
                               '    ul.innerHTML = \'<li class="muted">Belum ada '
                               "notifikasi.</li>';\n"
                               '    return;\n'
                               '  }\n'
                               '  for (const n of items) {\n'
                               '    const li = document.createElement("li");\n'
                               '    li.className = n.severity;\n'
                               '    const time = document.createElement("time");\n'
                               '    time.textContent = n.created_at;\n'
                               '    li.append(time, n.message);\n'
                               '    ul.append(li);\n'
                               '  }\n'
                               '}\n'
                               '\n'
                               'function renderHistory(rows) {\n'
                               '  const body = $("#hist-body");\n'
                               '  body.innerHTML = "";\n'
                               '  if (!rows.length) {\n'
                               '    body.innerHTML = \'<tr><td colspan="6" class="muted">Tidak ada '
                               "data pada rentang ini.</td></tr>';\n"
                               '    return;\n'
                               '  }\n'
                               '  for (const r of rows) {\n'
                               '    const tr = document.createElement("tr");\n'
                               '    [r.recorded_at, `${r.level_pct.toFixed(0)}% '
                               '(${r.level_cm.toFixed(1)} cm)`,\n'
                               '     `${r.volume_l.toFixed(0)} L`, `${r.temperature_c.toFixed(1)} '
                               '°C`,\n'
                               '     r.ph.toFixed(2), `${r.turbidity_ntu.toFixed(1)} '
                               'NTU`].forEach((v) => {\n'
                               '      const td = document.createElement("td");\n'
                               '      td.textContent = v;\n'
                               '      tr.append(td);\n'
                               '    });\n'
                               '    body.append(tr);\n'
                               '  }\n'
                               '}\n'
                               '\n'
                               'async function loadHistory() {\n'
                               '  const p = new URLSearchParams();\n'
                               '  const f = new FormData($("#hist-form"));\n'
                               '  for (const k of ["start", "end"]) if (f.get(k)) p.set(k, '
                               'f.get(k));\n'
                               '  p.set("limit", 50);\n'
                               '  renderHistory(await api(`/api/history?${p}`));\n'
                               '}\n'
                               '\n'
                               'async function refresh() {\n'
                               '  try {\n'
                               '    renderLatest(await api("/api/sensor/latest"));\n'
                               '    renderNotifs(await api("/api/notifications?limit=10"));\n'
                               '    await loadHistory();\n'
                               '  } catch (e) {\n'
                               '    $("#updated").textContent = e.message;\n'
                               '  }\n'
                               '}\n'
                               '\n'
                               'async function loadConfig() {\n'
                               '  const cfg = await api("/api/tank-config");\n'
                               '  const form = $("#cfg-form");\n'
                               '  for (const k of ["name", "capacity_l", "height_cm", '
                               '"diameter_cm"]) form.elements[k].value = cfg[k];\n'
                               '  $("#tank-name").textContent = `${cfg.name} · ${cfg.capacity_l} L '
                               '· tinggi ${cfg.height_cm} cm · diameter ${cfg.diameter_cm} cm`;\n'
                               '}\n'
                               '\n'
                               '$("#cfg-form").addEventListener("submit", async (e) => {\n'
                               '  e.preventDefault();\n'
                               '  const body = Object.fromEntries(new FormData(e.target));\n'
                               '  try {\n'
                               '    await api("/api/tank-config", {\n'
                               '      method: "PUT", headers: { "Content-Type": "application/json" '
                               '}, body: JSON.stringify(body),\n'
                               '    });\n'
                               '    $("#cfg-msg").textContent = "Konfigurasi tersimpan.";\n'
                               '    await loadConfig();\n'
                               '  } catch (err) {\n'
                               '    $("#cfg-msg").textContent = err.message;\n'
                               '  }\n'
                               '});\n'
                               '\n'
                               '$("#hist-form").addEventListener("submit", (e) => { '
                               'e.preventDefault(); loadHistory(); });\n'
                               '$("#hist-reset").addEventListener("click", () => { '
                               '$("#hist-form").reset(); loadHistory(); });\n'
                               '\n'
                               'loadConfig();\n'
                               'refresh();\n'
                               'setInterval(refresh, REFRESH_MS);\n',
 'app/templates/index.html': '<!doctype html>\n'
                             '<html lang="id">\n'
                             '<head>\n'
                             '  <meta charset="utf-8">\n'
                             '  <meta name="viewport" content="width=device-width, '
                             'initial-scale=1">\n'
                             '  <title>Digital Twin Tangki Air</title>\n'
                             '  <link rel="stylesheet" href="{{ url_for(\'static\', '
                             'filename=\'css/style.css\') }}">\n'
                             '</head>\n'
                             '<body>\n'
                             '  <header class="top">\n'
                             '    <h1>Digital Twin Tangki Air</h1>\n'
                             '    <p id="tank-name" class="muted">Memuat data tangki…</p>\n'
                             '  </header>\n'
                             '\n'
                             '  <main>\n'
                             '    <section class="twin" aria-label="Visualisasi tangki">\n'
                             '      <svg id="tank" viewBox="0 0 200 280" role="img" '
                             'aria-label="Tangki air">\n'
                             '        <defs>\n'
                             '          <clipPath id="inside"><rect x="30" y="20" width="140" '
                             'height="240" rx="14"/></clipPath>\n'
                             '        </defs>\n'
                             '        <rect class="tank-body" x="30" y="20" width="140" '
                             'height="240" rx="14"/>\n'
                             '        <g clip-path="url(#inside)">\n'
                             '          <rect id="water" class="water" x="30" y="260" width="140" '
                             'height="0"/>\n'
                             '        </g>\n'
                             '        <rect class="tank-outline" x="30" y="20" width="140" '
                             'height="240" rx="14"/>\n'
                             '      </svg>\n'
                             '      <div class="level">\n'
                             '        <strong id="level-pct">–</strong>\n'
                             '        <span id="level-detail" class="muted">Menunggu data '
                             'sensor</span>\n'
                             '      </div>\n'
                             '    </section>\n'
                             '\n'
                             '    <section class="panel">\n'
                             '      <div class="status-row">\n'
                             '        <h2>Kondisi air</h2>\n'
                             '        <span id="status" class="badge">–</span>\n'
                             '      </div>\n'
                             '      <dl class="readings">\n'
                             '        <div><dt>Suhu</dt><dd id="r-temp">–</dd></div>\n'
                             '        <div><dt>pH</dt><dd id="r-ph">–</dd></div>\n'
                             '        <div><dt>Kekeruhan</dt><dd id="r-turb">–</dd></div>\n'
                             '        <div><dt>Volume</dt><dd id="r-vol">–</dd></div>\n'
                             '      </dl>\n'
                             '      <p id="updated" class="muted"></p>\n'
                             '\n'
                             '      <h2>Notifikasi terbaru</h2>\n'
                             '      <ul id="notifs" class="notifs"><li class="muted">Belum ada '
                             'notifikasi.</li></ul>\n'
                             '    </section>\n'
                             '\n'
                             '    <section class="panel">\n'
                             '      <h2>Konfigurasi tangki</h2>\n'
                             '      <form id="cfg-form" class="grid">\n'
                             '        <label>Nama tangki <input name="name" required></label>\n'
                             '        <label>Kapasitas (liter) <input name="capacity_l" '
                             'type="number" step="any" min="1" required></label>\n'
                             '        <label>Tinggi (cm) <input name="height_cm" type="number" '
                             'step="any" min="1" required></label>\n'
                             '        <label>Diameter (cm) <input name="diameter_cm" type="number" '
                             'step="any" min="1" required></label>\n'
                             '        <button type="submit">Simpan konfigurasi</button>\n'
                             '      </form>\n'
                             '      <p id="cfg-msg" class="muted" role="status"></p>\n'
                             '    </section>\n'
                             '\n'
                             '    <section class="panel wide">\n'
                             '      <h2>Riwayat pengukuran</h2>\n'
                             '      <form id="hist-form" class="grid inline">\n'
                             '        <label>Dari <input name="start" '
                             'type="datetime-local"></label>\n'
                             '        <label>Sampai <input name="end" '
                             'type="datetime-local"></label>\n'
                             '        <button type="submit">Tampilkan</button>\n'
                             '        <button type="button" id="hist-reset" class="ghost">Hapus '
                             'filter</button>\n'
                             '      </form>\n'
                             '      <div class="table-wrap">\n'
                             '        <table>\n'
                             '          '
                             '<thead><tr><th>Waktu</th><th>Level</th><th>Volume</th><th>Suhu</th><th>pH</th><th>Kekeruhan</th></tr></thead>\n'
                             '          <tbody id="hist-body"><tr><td colspan="6" '
                             'class="muted">Belum ada data.</td></tr></tbody>\n'
                             '        </table>\n'
                             '      </div>\n'
                             '    </section>\n'
                             '  </main>\n'
                             '\n'
                             '  <script src="{{ url_for(\'static\', filename=\'js/dashboard.js\') '
                             '}}"></script>\n'
                             '</body>\n'
                             '</html>\n',
 'config.py': '"""Konfigurasi utama aplikasi Digital Twin Tangki Air."""\n'
              'import os\n'
              '\n'
              'BASE_DIR = os.path.abspath(os.path.dirname(__file__))\n'
              'PORT = 5000\n'
              '\n'
              '# Database\n'
              'DB_PATH = os.path.join(BASE_DIR, "data", "tangki.db")\n'
              '\n'
              '# Sumber data sensor (API simulasi bawaan proyek ini; ganti ke sensor asli di '
              'Sprint berikutnya)\n'
              'SENSOR_API_URL = f"http://127.0.0.1:{PORT}/sim/sensor"\n'
              'START_POLLER = True\n'
              'POLL_INTERVAL_S = 5\n'
              '\n'
              '# Ambang batas notifikasi\n'
              'LEVEL_LOW_PCT = 20\n'
              'LEVEL_HIGH_PCT = 90\n'
              'TEMP_MIN_C = 15\n'
              'TEMP_MAX_C = 35\n'
              'PH_MIN = 6.5\n'
              'PH_MAX = 8.5\n'
              'TURBIDITY_MAX_NTU = 5\n'
              '\n'
              '# Jeda minimal (detik) sebelum notifikasi jenis yang sama dicatat lagi\n'
              'NOTIF_COOLDOWN_S = 60\n',
 'data/.gitkeep': '',
 'docs/Perhitungan_Function_Point_Sprint_1.md': '# Perhitungan Function Point – Sprint 1\n'
                                                '\n'
                                                '## Daftar Fitur & Perhitungan UFC\n'
                                                '\n'
                                                '| No. | Nama Fungsi | Jenis | Tingkat Kerumitan | '
                                                'Bobot |\n'
                                                '| --- | --- | --- | --- | --- |\n'
                                                '| 1 | Input data konfigurasi tangki (kapasitas, '
                                                'tinggi, diameter) | EI | Sederhana | 3 |\n'
                                                '| 2 | Input data sensor (ketinggian, suhu, '
                                                'kualitas, data simulasi) | EI | Sedang | 4 |\n'
                                                '| 3 | Tampilan visualisasi tangki & level air | '
                                                'EO | Sedang | 5 |\n'
                                                '| 4 | Dashboard status & indikator kualitas air | '
                                                'EO | Sedang | 5 |\n'
                                                '| 5 | Tampilan notifikasi batas kritis / anomali '
                                                '| EO | Sederhana | 4 |\n'
                                                '| 6 | Lihat riwayat data pengukuran | EQ | '
                                                'Sederhana | 3 |\n'
                                                '| 7 | Cari data berdasarkan rentang waktu | EQ | '
                                                'Sedang | 4 |\n'
                                                '| 8 | Simpan data konfigurasi & pengguna | ILF | '
                                                'Sederhana | 7 |\n'
                                                '| 9 | Simpan rekaman data sensor | ILF | Sedang | '
                                                '10 |\n'
                                                '| 10 | Simpan catatan notifikasi | ILF | '
                                                'Sederhana | 7 |\n'
                                                '| 11 | Ambil data dari simulasi API sensor | EIF '
                                                '| Sederhana | 5 |\n'
                                                '| | **TOTAL UFC** | | | **57** |\n'
                                                '\n'
                                                '## Penilaian 14 Faktor Penyesuaian\n'
                                                '\n'
                                                '| No. | Faktor Pengaruh Sistem | Nilai (0–5) |\n'
                                                '| --- | --- | --- |\n'
                                                '| 1 | Komunikasi data | 2 |\n'
                                                '| 2 | Fungsi terdistribusi | 1 |\n'
                                                '| 3 | Kinerja | 2 |\n'
                                                '| 4 | Konfigurasi perangkat keras | 1 |\n'
                                                '| 5 | Tingkat transaksi | 2 |\n'
                                                '| 6 | Masukan data pengguna | 2 |\n'
                                                '| 7 | Kemudahan efisiensi pengguna | 3 |\n'
                                                '| 8 | Pembaruan data langsung | 2 |\n'
                                                '| 9 | Kompleksitas pemrosesan | 2 |\n'
                                                '| 10 | Penggunaan kembali | 2 |\n'
                                                '| 11 | Kemudahan instalasi | 2 |\n'
                                                '| 12 | Kemudahan operasi | 3 |\n'
                                                '| 13 | Banyaknya perangkat | 1 |\n'
                                                '| 14 | Kemudahan perubahan | 3 |\n'
                                                '| | **JUMLAH ΣF** | **28** |\n'
                                                '\n'
                                                '**Perhitungan VAF:**\n'
                                                '\n'
                                                '```\n'
                                                'VAF = 0,65 + (0,01 × ΣF)\n'
                                                '    = 0,65 + (0,01 × 28)\n'
                                                '    = 0,65 + 0,28\n'
                                                '    = 0,93\n'
                                                '```\n'
                                                '\n'
                                                '## Hasil Akhir Function Point\n'
                                                '\n'
                                                '```\n'
                                                'FP  = UFC × VAF\n'
                                                '    = 57 × 0,93\n'
                                                '    = 53,01\n'
                                                '```\n'
                                                '\n'
                                                '## Kesimpulan\n'
                                                '\n'
                                                'Ukuran fungsional proyek **Perancangan Digital '
                                                'Twin Tangki Air untuk Monitoring Ketinggian dan '
                                                'Kondisi Air Secara Real-Time** pada tahap Sprint '
                                                '1 adalah **53,01 Function Point**.\n'
                                                '\n'
                                                'Nilai ini mencerminkan cakupan pekerjaan yang '
                                                'wajar untuk proyek mahasiswa: pemantauan data, '
                                                'visualisasi, notifikasi, penyimpanan riwayat, dan '
                                                'koneksi data simulasi sesuai tujuan dan ruang '
                                                'lingkup yang disepakati.\n',
 'docs/Product_Backlog_dan_Sprint_1_Backlog.md': '# Product Backlog & Sprint 1 Backlog\n'
                                                 '\n'
                                                 '**Proyek:** Perancangan Digital Twin Tangki Air '
                                                 'untuk Monitoring Ketinggian dan Kondisi Air '
                                                 'Secara Real-Time\n'
                                                 '\n'
                                                 '---\n'
                                                 '\n'
                                                 '## 1. Product Backlog\n'
                                                 '\n'
                                                 'Prioritas: **Tinggi** = fondasi/inti sistem, '
                                                 '**Sedang** = fitur pendukung, **Rendah** = '
                                                 'pengembangan lanjutan.\n'
                                                 'Bobot FP diambil dari perhitungan Function Point '
                                                 'Sprint 1 (UFC).\n'
                                                 '\n'
                                                 '| ID | Fitur | User Story | Jenis FP | Bobot FP '
                                                 '| Prioritas | Sprint |\n'
                                                 '| --- | --- | --- | --- | --- | --- | --- |\n'
                                                 '| PBI-01 | Konfigurasi tangki | Sebagai '
                                                 'operator, saya ingin memasukkan kapasitas, '
                                                 'tinggi, dan diameter tangki agar model digital '
                                                 'sesuai tangki asli. | EI | 3 | Tinggi | 1 |\n'
                                                 '| PBI-02 | Input data sensor | Sebagai sistem, '
                                                 'saya ingin menerima data ketinggian, suhu, dan '
                                                 'kualitas air agar kondisi tangki dapat dipantau. '
                                                 '| EI | 4 | Tinggi | 1 |\n'
                                                 '| PBI-03 | Visualisasi tangki & level air | '
                                                 'Sebagai operator, saya ingin melihat gambar '
                                                 'tangki dengan level air yang bergerak sesuai '
                                                 'data agar kondisi air mudah dipahami. | EO | 5 | '
                                                 'Tinggi | 1 |\n'
                                                 '| PBI-04 | Dashboard status & kualitas air | '
                                                 'Sebagai operator, saya ingin melihat ringkasan '
                                                 'status dan indikator kualitas air dalam satu '
                                                 'halaman. | EO | 5 | Tinggi | 1 |\n'
                                                 '| PBI-05 | Notifikasi batas kritis / anomali | '
                                                 'Sebagai operator, saya ingin mendapat peringatan '
                                                 'saat air terlalu rendah, terlalu tinggi, atau '
                                                 'kualitas menurun agar dapat segera bertindak. | '
                                                 'EO | 4 | Tinggi | 1 |\n'
                                                 '| PBI-06 | Riwayat data pengukuran | Sebagai '
                                                 'operator, saya ingin melihat riwayat pengukuran '
                                                 'untuk memantau perubahan dari waktu ke waktu. | '
                                                 'EQ | 3 | Sedang | 1 |\n'
                                                 '| PBI-07 | Pencarian berdasarkan rentang waktu | '
                                                 'Sebagai operator, saya ingin menyaring data '
                                                 'berdasarkan tanggal/jam agar mudah menemukan '
                                                 'data tertentu. | EQ | 4 | Sedang | 1 |\n'
                                                 '| PBI-08 | Penyimpanan konfigurasi & pengguna | '
                                                 'Sebagai sistem, saya ingin menyimpan data '
                                                 'konfigurasi tangki dan pengguna agar tidak '
                                                 'hilang. | ILF | 7 | Tinggi | 1 |\n'
                                                 '| PBI-09 | Penyimpanan rekaman data sensor | '
                                                 'Sebagai sistem, saya ingin menyimpan setiap '
                                                 'rekaman sensor sebagai dasar riwayat dan '
                                                 'analisis. | ILF | 10 | Tinggi | 1 |\n'
                                                 '| PBI-10 | Penyimpanan catatan notifikasi | '
                                                 'Sebagai sistem, saya ingin menyimpan log '
                                                 'notifikasi agar kejadian anomali dapat '
                                                 'ditelusuri. | ILF | 7 | Sedang | 1 |\n'
                                                 '| PBI-11 | Pengambilan data dari API simulasi '
                                                 'sensor | Sebagai sistem, saya ingin mengambil '
                                                 'data dari API simulasi agar pengembangan bisa '
                                                 'berjalan tanpa sensor fisik. | EIF | 5 | Tinggi '
                                                 '| 1 |\n'
                                                 '| PBI-12 | Login & manajemen peran pengguna | '
                                                 'Sebagai admin, saya ingin mengatur akun dan hak '
                                                 'akses agar sistem aman. | – | TBD | Sedang | 2 '
                                                 '|\n'
                                                 '| PBI-13 | Grafik tren ketinggian & kualitas air '
                                                 '| Sebagai operator, saya ingin melihat grafik '
                                                 'tren agar pola perubahan terlihat jelas. | – | '
                                                 'TBD | Sedang | 2 |\n'
                                                 '| PBI-14 | Ekspor laporan (CSV/PDF) | Sebagai '
                                                 'operator, saya ingin mengunduh data riwayat '
                                                 'sebagai laporan. | – | TBD | Sedang | 2 |\n'
                                                 '| PBI-15 | Pengaturan ambang batas notifikasi | '
                                                 'Sebagai admin, saya ingin mengubah batas kritis '
                                                 'sendiri tanpa mengubah kode. | – | TBD | Sedang '
                                                 '| 2 |\n'
                                                 '| PBI-16 | Integrasi sensor fisik (mis. '
                                                 'ESP32/MQTT) | Sebagai sistem, saya ingin '
                                                 'menerima data dari sensor sungguhan menggantikan '
                                                 'simulasi. | – | TBD | Rendah | 3 |\n'
                                                 '| PBI-17 | Prediksi waktu tangki habis/penuh | '
                                                 'Sebagai operator, saya ingin perkiraan kapan '
                                                 'tangki kosong/penuh agar bisa merencanakan '
                                                 'pengisian. | – | TBD | Rendah | 3 |\n'
                                                 '| PBI-18 | Visualisasi 3D tangki | Sebagai '
                                                 'operator, saya ingin tampilan 3D yang lebih '
                                                 'realistis sebagai digital twin. | – | TBD | '
                                                 'Rendah | 3 |\n'
                                                 '| PBI-19 | Pengujian menyeluruh & dokumentasi '
                                                 'akhir | Sebagai tim, kami ingin sistem teruji '
                                                 'dan terdokumentasi untuk penyerahan proyek. | – '
                                                 '| TBD | Tinggi | 3 |\n'
                                                 '\n'
                                                 '> Sprint 2 dan 3 bersifat rencana awal dan dapat '
                                                 'disesuaikan setelah Sprint Review.\n'
                                                 '\n'
                                                 '---\n'
                                                 '\n'
                                                 '## 2. Sprint 1 Backlog\n'
                                                 '\n'
                                                 '### Sprint Goal\n'
                                                 '\n'
                                                 'Menghasilkan versi awal sistem yang dapat '
                                                 'menerima data simulasi sensor, menyimpannya, '
                                                 'menampilkannya pada visualisasi tangki dan '
                                                 'dashboard, serta memberi notifikasi saat kondisi '
                                                 'kritis.\n'
                                                 '\n'
                                                 '### Ringkasan\n'
                                                 '\n'
                                                 '| Item | Keterangan |\n'
                                                 '| --- | --- |\n'
                                                 '| Jumlah PBI | 11 (PBI-01 s.d. PBI-11) |\n'
                                                 '| Ukuran fungsional | UFC 57 → **53,01 FP** (VAF '
                                                 '0,93) |\n'
                                                 '| Total estimasi tugas | 108 jam |\n'
                                                 '| Durasi sprint | 2 minggu *(asumsi, sesuaikan '
                                                 'dengan jadwal tim)* |\n'
                                                 '\n'
                                                 '### Daftar Tugas\n'
                                                 '\n'
                                                 'Urutan tugas mengikuti ketergantungan: database '
                                                 'dan simulator dulu, lalu fitur yang memakainya.\n'
                                                 '\n'
                                                 '| ID Tugas | PBI | Tugas | Estimasi (jam) | '
                                                 'Status |\n'
                                                 '| --- | --- | --- | --- | --- |\n'
                                                 '| T-01 | PBI-08 | Merancang skema database '
                                                 '(konfigurasi, pengguna, sensor, notifikasi) | 4 '
                                                 '| To Do |\n'
                                                 '| T-02 | PBI-08 | Membuat tabel & model '
                                                 'konfigurasi tangki dan pengguna | 4 | To Do |\n'
                                                 '| T-03 | PBI-09 | Membuat tabel rekaman sensor '
                                                 'beserta indeks waktu | 4 | To Do |\n'
                                                 '| T-04 | PBI-10 | Membuat tabel catatan '
                                                 'notifikasi | 3 | To Do |\n'
                                                 '| T-05 | PBI-11 | Membuat API simulasi sensor '
                                                 '(ketinggian, suhu, kualitas air) | 8 | To Do |\n'
                                                 '| T-06 | PBI-11 | Membuat layanan pengambilan '
                                                 'data berkala dari API simulasi | 6 | To Do |\n'
                                                 '| T-07 | PBI-01 | Membuat form konfigurasi '
                                                 'tangki dengan validasi | 6 | To Do |\n'
                                                 '| T-08 | PBI-01 | Menyimpan dan mengubah '
                                                 'konfigurasi tangki ke database | 3 | To Do |\n'
                                                 '| T-09 | PBI-02 | Membuat proses input data '
                                                 'sensor dengan validasi | 6 | To Do |\n'
                                                 '| T-10 | PBI-02 | Menyimpan rekaman sensor ke '
                                                 'database | 3 | To Do |\n'
                                                 '| T-11 | PBI-03 | Membuat model visualisasi '
                                                 'tangki | 10 | To Do |\n'
                                                 '| T-12 | PBI-03 | Menghubungkan level air pada '
                                                 'visualisasi dengan data real-time | 6 | To Do |\n'
                                                 '| T-13 | PBI-04 | Membuat tata letak halaman '
                                                 'dashboard | 6 | To Do |\n'
                                                 '| T-14 | PBI-04 | Membuat indikator kualitas air '
                                                 '(suhu dan parameter kualitas) | 6 | To Do |\n'
                                                 '| T-15 | PBI-05 | Membuat logika ambang batas '
                                                 'dan deteksi anomali | 6 | To Do |\n'
                                                 '| T-16 | PBI-05 | Menampilkan notifikasi di '
                                                 'antarmuka dan menyimpannya ke log | 5 | To Do |\n'
                                                 '| T-17 | PBI-06 | Membuat halaman tabel riwayat '
                                                 'pengukuran | 5 | To Do |\n'
                                                 '| T-18 | PBI-07 | Menambahkan filter rentang '
                                                 'waktu pada riwayat | 5 | To Do |\n'
                                                 '| T-19 | Umum | Pengujian fungsional seluruh '
                                                 'fitur Sprint 1 | 8 | To Do |\n'
                                                 '| T-20 | Umum | Integrasi akhir dan persiapan '
                                                 'demo Sprint Review | 4 | To Do |\n'
                                                 '| | | **TOTAL** | **108** | |\n'
                                                 '\n'
                                                 '### Definition of Done\n'
                                                 '\n'
                                                 '- Fitur berjalan sesuai user story dan lolos '
                                                 'pengujian fungsional.\n'
                                                 '- Data tersimpan dan dapat ditampilkan kembali '
                                                 'dengan benar.\n'
                                                 '- Tidak ada kesalahan kritis (error) yang '
                                                 'tersisa pada alur utama.\n'
                                                 '- Kode tersimpan di repositori bersama.\n'
                                                 '- Fitur dapat didemokan pada Sprint Review.\n'
                                                 '\n'
                                                 '### Catatan\n'
                                                 '\n'
                                                 '- Kolom penanggung jawab (PIC) belum diisi '
                                                 'karena anggota tim belum diketahui; bisa '
                                                 'ditambahkan.\n'
                                                 '- Estimasi jam adalah perkiraan awal dan '
                                                 'sebaiknya dikonfirmasi bersama tim pada Sprint '
                                                 'Planning.\n'
                                                 '- Isi Sprint 2 dan 3 adalah usulan; bobot FP-nya '
                                                 'baru bisa dihitung setelah fitur dirinci.\n',
 'docs/README.md': '# Folder Dokumen Sprint 1\n'
                   '\n'
                   '| Dokumen | Status |\n'
                   '| --- | --- |\n'
                   '| Project Charter | Letakkan file di sini (`Project_Charter.docx`) |\n'
                   '| Perhitungan Function Point | `Perhitungan_Function_Point_Sprint_1.md` |\n'
                   '| Product Backlog & Sprint 1 Backlog | '
                   '`Product_Backlog_dan_Sprint_1_Backlog.md` |\n'
                   '| Rancangan UX/UI (wireframe/mockup) | Letakkan ekspor gambar/PDF di sini |\n'
                   '| Rancangan sistem (flowchart, arsitektur, ERD) | Letakkan ekspor gambar/PDF '
                   'di sini |\n',
 'requirements.txt': 'Flask>=3.0\npytest>=8.0\n',
 'run.py': 'from app import create_app\n'
           'import config\n'
           '\n'
           'app = create_app()\n'
           '\n'
           'if __name__ == "__main__":\n'
           '    # use_reloader=False agar poller data sensor tidak berjalan dua kali\n'
           '    app.run(host="127.0.0.1", port=config.PORT, debug=True, use_reloader=False)\n',
 'tests/conftest.py': 'import os\n'
                      'import sys\n'
                      '\n'
                      'import pytest\n'
                      '\n'
                      'sys.path.insert(0, '
                      'os.path.dirname(os.path.dirname(os.path.abspath(__file__))))\n'
                      'from app import create_app  # noqa: E402\n'
                      '\n'
                      '\n'
                      '@pytest.fixture\n'
                      'def client(tmp_path):\n'
                      '    app = create_app({\n'
                      '        "TESTING": True,\n'
                      '        "START_POLLER": False,\n'
                      '        "DB_PATH": str(tmp_path / "test.db"),\n'
                      '    })\n'
                      '    return app.test_client()\n',
 'tests/test_api.py': 'GOOD = {"level_cm": 100, "temperature_c": 27, "ph": 7.2, "turbidity_ntu": '
                      '1.5}\n'
                      '\n'
                      '\n'
                      'def test_default_config_exists(client):\n'
                      '    cfg = client.get("/api/tank-config").get_json()\n'
                      '    assert cfg["capacity_l"] == 1000 and cfg["height_cm"] == 150\n'
                      '\n'
                      '\n'
                      'def test_update_config_and_validation(client):\n'
                      '    ok = client.put("/api/tank-config", json={\n'
                      '        "name": "Tangki B", "capacity_l": 500, "height_cm": 100, '
                      '"diameter_cm": 80})\n'
                      '    assert ok.status_code == 200 and ok.get_json()["name"] == "Tangki B"\n'
                      '    bad = client.put("/api/tank-config", json={\n'
                      '        "capacity_l": -1, "height_cm": 100, "diameter_cm": 80})\n'
                      '    assert bad.status_code == 400\n'
                      '\n'
                      '\n'
                      'def test_post_sensor_stores_and_computes_level(client):\n'
                      '    res = client.post("/api/sensor", json=GOOD)\n'
                      '    assert res.status_code == 201\n'
                      '    reading = res.get_json()["reading"]\n'
                      '    assert round(reading["level_pct"], 1) == 66.7\n'
                      '    latest = client.get("/api/sensor/latest").get_json()\n'
                      '    assert latest["reading"]["id"] == reading["id"]\n'
                      '\n'
                      '\n'
                      'def test_sensor_validation(client):\n'
                      '    res = client.post("/api/sensor", json={**GOOD, "ph": 20})\n'
                      '    assert res.status_code == 400\n'
                      '    res = client.post("/api/sensor", json={"level_cm": 10})\n'
                      '    assert res.status_code == 400\n'
                      '\n'
                      '\n'
                      'def test_low_level_creates_single_notification(client):\n'
                      '    low = {**GOOD, "level_cm": 10}\n'
                      '    client.post("/api/sensor", json=low)\n'
                      '    client.post("/api/sensor", json=low)  # dalam masa jeda -> tidak dobel\n'
                      '    notifs = client.get("/api/notifications").get_json()\n'
                      '    assert [n["kind"] for n in notifs] == ["level_low"]\n'
                      '\n'
                      '\n'
                      'def test_history_filter(client):\n'
                      '    client.post("/api/sensor", json=GOOD)\n'
                      '    assert len(client.get("/api/history").get_json()) == 1\n'
                      '    assert client.get("/api/history?start=2999-01-01").get_json() == []\n'
                      '    assert client.get("/api/history?end=2000-01-01").get_json() == []\n'
                      '\n'
                      '\n'
                      'def test_simulator_returns_valid_reading(client):\n'
                      '    data = client.get("/sim/sensor").get_json()\n'
                      '    assert set(data) == {"level_cm", "temperature_c", "ph", '
                      '"turbidity_ntu"}\n'
                      '    assert client.post("/api/sensor", json=data).status_code == 201\n'
                      '\n'
                      '\n'
                      'def test_dashboard_page(client):\n'
                      '    assert client.get("/").status_code == 200\n'}


def main():
    root = "digital-twin-tangki-air"
    for path, content in FILES.items():
        full = os.path.join(root, *path.split("/"))
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
    print(f"Selesai: {len(FILES)} file dibuat di folder '{root}/'.")
    print("Langkah berikutnya: cd digital-twin-tangki-air && pip install -r requirements.txt && python run.py")


if __name__ == "__main__":
    main()
